from __future__ import annotations

from pathlib import Path
import typer

from racerapi.core.logger import get_logger

logger = get_logger(__name__)


def _alembic_env_py() -> str:
    return '''"""Alembic environment for RacerAPI - autogenerated minimal file."""
import os
import sys
from logging.config import fileConfig

from sqlalchemy import engine_from_config
from sqlalchemy import pool

from alembic import context

# Ensure `src` is importable
ROOT = os.path.dirname(os.path.dirname(__file__))
SRC = os.path.join(ROOT, 'src')
if SRC not in sys.path:
    sys.path.insert(0, SRC)

# this is the Alembic Config object, which provides
# access to the values within the .ini file in use.
config = context.config

# Interpret the config file for Python logging if present. Be tolerant to minimal ini.
try:
    fileConfig(config.config_file_name)
except Exception:
    pass

# Import all models so metadata is populated
try:
    from racerapi.db import models_registry  # noqa: F401
    from racerapi.db.base import Base

    target_metadata = Base.metadata
except Exception:
    target_metadata = None


def get_url():
    try:
        from racerapi.core.config import settings

        return settings.database_url
    except Exception:
        return config.get_main_option("sqlalchemy.url")


def run_migrations_offline():
    url = get_url()
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online():
    configuration = config.get_section(config.config_ini_section)
    configuration["sqlalchemy.url"] = get_url()
    connectable = engine_from_config(
        configuration,
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        context.configure(
            connection=connection, target_metadata=target_metadata
        )

        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
'''


def _init_alembic_files(root: Path) -> None:
    """Create an embedded minimal alembic environment if missing."""
    ini = root / "alembic.ini"
    alembic_dir = root / "alembic"
    versions = alembic_dir / "versions"
    if not alembic_dir.exists():
        alembic_dir.mkdir(parents=True, exist_ok=True)
    if not versions.exists():
        versions.mkdir(parents=True, exist_ok=True)

    if not ini.exists():
        ini.write_text(
            """
[alembic]
script_location = alembic
sqlalchemy.url = driver://user:pass@localhost/dbname

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console

[handler_console]
class = StreamHandler
args = (sys.stdout,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
"""
        )

    env = alembic_dir / "env.py"
    if not env.exists():
        env.write_text(_alembic_env_py())


def db_command(command: str) -> None:
    try:
        from alembic.config import Config
        from alembic import command as alembic_command
    except Exception:
        typer.echo("Alembic is not installed. Add 'alembic' to dependencies.")
        raise typer.Exit(code=2)

    cfg_path = Path.cwd() / "alembic.ini"
    # Initialize minimal alembic environment when missing
    if not cfg_path.exists() or not (Path.cwd() / "alembic").exists():
        typer.echo("Initializing alembic environment")
        _init_alembic_files(Path.cwd())

    cfg = Config(str(cfg_path))

    if command == "init":
        typer.echo("Alembic environment ensured")
    elif command == "migrate":
        typer.echo("Creating migration (autogenerate)")
        alembic_command.revision(cfg, autogenerate=True, message="auto")
    elif command == "upgrade":
        typer.echo("Applying migrations")
        alembic_command.upgrade(cfg, "head")
    else:
        typer.echo("Unknown command")
