from __future__ import annotations

import importlib
import textwrap
from pathlib import Path
from typing import Optional

import typer

from racerapi.cli.context import CLIContext
from racerapi.cli.utils import write_file


generate_app = typer.Typer()
TEMPLATE_VERSION = "1"


def _find_templates_dir() -> Path:
    return Path(__file__).resolve().parents[2] / "templates" / "module"


def _render_template_file(path: Path, **ctx: str) -> str:
    tpl = path.read_text(encoding="utf-8")
    return textwrap.dedent(tpl).lstrip("\n").format(**ctx)


def _validate_name(name: str) -> None:
    if not name.isidentifier() or name != name.lower():
        typer.echo("Invalid module name: must be a valid lowercase python identifier")
        raise typer.Exit(code=2)


def _target_dir(name: str) -> tuple[Path, str]:
    cwd = Path.cwd()
    src_dir = cwd / "src"
    target_pkg = None
    if src_dir.exists():
        for child in src_dir.iterdir():
            if child.is_dir() and (child / "__init__.py").exists():
                if child.name != "racerapi":
                    target_pkg = child.name
                    break
    if target_pkg:
        return src_dir / target_pkg / "modules" / name, target_pkg
    return src_dir / "racerapi" / "modules" / name, "racerapi"


def _template_header() -> str:
    return f"# Generated by racerapi (template_version={TEMPLATE_VERSION})\n\n"


def _validate_module_import(package: str, module_name: str) -> None:
    modname = f"{package}.modules.{module_name}.api"
    try:
        module = importlib.import_module(modname)
    except Exception as exc:
        raise typer.Exit(f"Failed to validate generated module: {exc}") from exc
    if not hasattr(module, "router"):
        raise typer.Exit(f"Generated module {module_name} does not expose a router")


def _pythonize_name(name: str) -> tuple[str, str, str]:
    singular = name[:-1] if name.endswith("s") else name
    return name, singular, singular.capitalize()


@generate_app.command("module")
def generate_module(name: str, ctx: typer.Context) -> None:
    """Generate a new module skeleton under src/<pkg>/modules/<name>."""
    context: CLIContext = ctx.obj
    _validate_name(name)
    target, package_name = _target_dir(name)
    write_file(target / ".racerapi_template_version", TEMPLATE_VERSION, context)
    name, singular, Name = _pythonize_name(name)
    table_name = name if name.endswith("s") else f"{name}s"
    files = {
        "api.py": "api.py.tpl",
        "service.py": "service.py.tpl",
        "repo.py": "repo.py.tpl",
        "schemas.py": "schemas.py.tpl",
        "models.py": "models.py.tpl",
        "deps.py": "deps.py.tpl",
        f"tests/test_module_{name}_api.py": "tests.py.tpl",
    }
    templates_dir = _find_templates_dir()
    for fname, tpl_name in sorted(files.items()):
        content = _render_template_file(
            templates_dir / tpl_name,
            name=name,
            singular=singular,
            Name=Name,
            table_name=table_name,
        )
        write_file(target / fname, _template_header() + content, context)

    typer.echo(f"Generated module '{name}' at {target}")
    if not context.dry_run:
        try:
            if package_name != "racerapi":
                import sys

                src_dir = Path.cwd() / "src"
                if str(src_dir) not in sys.path:
                    sys.path.insert(0, str(src_dir))
            _validate_module_import(package_name, name)
        except typer.Exit:
            raise
        except Exception as exc:
            raise typer.Exit(f"Failed to validate generated module import: {exc}") from exc


@generate_app.command("service")
def generate_service(name: str, ctx: typer.Context) -> None:
    """Generate a service file for an existing module."""
    context: CLIContext = ctx.obj
    target, _ = _target_dir(name)
    if not target.exists():
        raise typer.Exit("Module does not exist. Generate module first.")
    file_path = target / "service.py"
    if file_path.exists() and not context.force:
        raise typer.Exit(f"Service already exists: {file_path}")
    name, singular, Name = _pythonize_name(name)
    write_file(
        file_path,
        _template_header()
        + _render_template_file(
            _find_templates_dir() / "service.py.tpl",
            name=name,
            singular=singular,
            Name=Name,
            table_name=name if name.endswith("s") else f"{name}s",
        ),
        context,
    )
    typer.echo(f"Generated service for module '{name}'")


@generate_app.command("resource")
def generate_resource(name: str, ctx: typer.Context) -> None:
    """Generate a full resource module with CRUD scaffolding."""
    context: CLIContext = ctx.obj
    target, _ = _target_dir(name)
    if not target.exists():
        generate_module(name, ctx)
        return
    try:
        generate_service(name, ctx)
    except typer.Exit:
        pass
    typer.echo(f"Generated resource '{name}'")
