from __future__ import annotations

from pathlib import Path
import typer


def new_project(project_name: str, path: str | None = None) -> None:
    """Create a new racerapi project skeleton."""
    pkg_root = Path(path or Path.cwd()) / project_name
    src = pkg_root / "src" / project_name
    src.mkdir(parents=True, exist_ok=True)
    (pkg_root / "README.md").write_text(f"# {project_name}\nGenerated by racerapi CLI\n")
    main_py = src / "main.py"
    if not main_py.exists():
        main_py.write_text(
            (
                "from racerapi.core.logger import configure_logging\n"
                "from racerapi.app import create_app\n\n"
                "configure_logging()\n"
                "app = create_app()\n\n"
                "if __name__ == '__main__':\n"
                "    import uvicorn\n\n"
                "    uvicorn.run(\"{pkg}.main:app\", host=\"127.0.0.1\", port=8000, reload=False)\n"
            ).replace("{pkg}", project_name)
        )
    typer.echo(f"Created project at {pkg_root}")
