[build-system]
requires = ["setuptools>=65.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "{project_name}"
version = "0.1.0"
description = "{project_name} application generated by RacerAPI CLI"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
{dependencies}
]
