"""Alembic environment for RacerAPI - autogenerated minimal file."""
import os
import sys
from logging.config import fileConfig

from sqlalchemy import engine_from_config
from sqlalchemy import pool

from alembic import context

# Ensure `src` is importable
ROOT = os.path.dirname(os.path.dirname(__file__))
SRC = os.path.join(ROOT, 'src')
if SRC not in sys.path:
    sys.path.insert(0, SRC)

# this is the Alembic Config object, which provides
# access to the values within the .ini file in use.
config = context.config

# Interpret the config file for Python logging if present. Be tolerant to minimal ini.
try:
    fileConfig(config.config_file_name)
except Exception:
    # Some minimal alembic.ini files may not contain full logging sections.
    pass

# add your model's MetaData object here
# Import model registry so all models are imported and metadata is populated
try:
    from racerapi.db import models_registry  # noqa: F401

    target_metadata = models_registry.metadata
except Exception:
    # fall back to Base metadata if registry import fails
    from racerapi.db.base import Base

    target_metadata = Base.metadata


def get_url():
    try:
        from racerapi.core.config import settings

        return settings.database_url
    except Exception:
        return config.get_main_option("sqlalchemy.url")


def run_migrations_offline():
    url = get_url()
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online():
    configuration = config.get_section(config.config_ini_section)
    configuration["sqlalchemy.url"] = get_url()
    connectable = engine_from_config(
        configuration,
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        context.configure(
            connection=connection, target_metadata=target_metadata
        )

        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
